Yaml output conifg
php-translation/documentation pull request #41
Opened 2019-02-11 20:31 UTC by aradoje

2019-02-12 20:54 UTC, Nyholm requested changes
Thank you for adding this.

2019-02-12 20:54 UTC, Nyholm commented on symfony/index.rst
> +          output_format: "yml"
Make it "xlf" because it is the default value. 

Also, xlf is the internet standard format for translation files.

2019-02-13 16:12 UTC, aradoje commented
My pleasure.

2019-02-13 16:17 UTC, Nyholm approved these changes
Thanks

2019-02-13 16:17 UTC, merged